import type { Metadata } from "next";
import { Bricolage_Grotesque } from "next/font/google";
import "./globals.css";
import Providers from "@/app/providers";

const font = Bricolage_Grotesque({
  variable: "--font-bricolage",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${font.variable} antialiased selection:bg-green-200/30`}
      >
        <Providers>{children}</Providers>
        <div className="fixed px-4 py-1.5 text-sm rounded-full backdrop-blur-lg bg-white/50 border border-white bottom-2.5 right-2.5">
          🧪 Currently in early development.
        </div>
      </body>
    </html>
  );
}
